name: 'SFTP Deploy'
description: 'Deploys a folder to a remote server via sftp.'
runs:
  using: "composite"
  steps:
  - name: 'Checkout GitHub Action'
    uses: actions/checkout@v4

  - name: 'Set up Python 3.12'
    uses: actions/setup-python@v5
    with:
      python-version: '3.12' 
  
  - name: Set GitHub Path
    run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
    shell: bash
    env:
      GITHUB_ACTION_PATH: ${{ github.action_path }}

  - name: "run python file"
    run: python ${GITHUB_ACTION_PATH}/main.py
    shell: bash